### ISSUE TITLE
Please make this easy to run for someone with no Rust experience

### ISSUE THREAD

**Issue by constanrine5d** [g0ddest/sm_motion_photo#6]
I don't know how to run this and get this issue with crate build:

-----------------------------------------------------------------------------------------------------------------------
error[E0599]: no function or associated item named `new` found for struct `MediaContext` in the current scope
   --> /Users/..../.cargo/git/checkouts/sm_motion_photo-5b585e73924016bc/9890a0e/src/lib.rs:125:59
    |
125 |                 let mut context = mp4parse::MediaContext::new();
    |                                                           ^^^ function or associated item not found in `MediaContext`

error[E0061]: this function takes 1 argument but 2 arguments were supplied
   --> /Users/..../.cargo/git/checkouts/sm_motion_photo-5b585e73924016bc/9890a0e/src/lib.rs:126:25
    |
126 |                 let _ = mp4parse::read_mp4(&mut video_content, &mut context);
    |                         ^^^^^^^^^^^^^^^^^^ ------------------  ------------ supplied 2 arguments
    |                         |
    |                         expected 1 argument

-----------------------------------------------------------------------------------------------------------------------

I don't know how else to contact you so I am marking this as an issue.

**Comment by g0ddest** [comment]
It's not connected with rust experience, it was just minor update on dependency mp4parse that broke their api. I've fixed it in new commit and 0.1.5 version.
Check this out!

**Comment by constanrine5d** [comment]
thx for quick response, this really saved me
